cleaning:
  postcode_col: postcode
  required_cols:
    - price
    - date
    - postcode
    - county
    - property_type
    - old/new
  col_headers:
    - transaction_id
    - price
    - date
    - postcode
    - property_type
    - old/new
    - duration
    - paon
    - saon
    - street
    - locality
    - town/city
    - district
    - county
    - ppdcategory_type
    - record_status
  dtype_map:
    price: float
    date: datetime
    postcode: string
    county: string
    property_type: string
    old/new: string
  clip_price: true
  clip_quantile: 0.99

augment_dataset:
  postcode_col: POSTCODE
  floor_col: TOTAL_FLOOR_AREA
  required_cols:
    - POSTCODE
    - TOTAL_FLOOR_AREA
  dtype_map:
    TOTAL_FLOOR_AREA: int
  col_headers:
    - LMK_KEY
    - POSTCODE
    - TOTAL_FLOOR_AREA
    - NUMBER_HABITABLE_ROOMS

train:
  numeric_features:
    - price
    - date
  cat_features:
    - property_type
    - old/new
    - district

feature_engineering:  
  use_district: true
  city_filter:
    city_col: county 
    filter_keywords:
      - london

parquet:
  sold_timestamp_col: date
  silver_partition_cols: 
    - sold_by
