cleaning:
  postcode_col: postcode
  loading_cols:
    - price
    - date
    - postcode
    - county
    - property_type
    - old/new
    - duration
  # add cols to load and update load function to pass in cols_to_load instead of required_cols
  required_cols:
    - price
    - date
    - postcode
    - county
    - property_type
    - is_new_build
    - is_leasehold
    - borough_price_trend
  col_headers:
    - transaction_id
    - price
    - date
    - postcode
    - property_type
    - old/new
    - duration
    - paon
    - saon
    - street
    - locality
    - town/city
    - district
    - county
    - ppdcategory_type
    - record_status
  rename_cols:
    old/new: is_new_build
    duration: is_leasehold  
  dtype_map:
    price: float
    date: datetime
    postcode: string
    county: string
    property_type: string
    is_new_build: string
    is_leasehold: string
  clip_price: true
  clip_quantile: 0.99

augment_dataset:
  postcode_col: POSTCODE
  floor_col: TOTAL_FLOOR_AREA
  required_cols:
    - POSTCODE
    - TOTAL_FLOOR_AREA
  dtype_map:
    TOTAL_FLOOR_AREA: int
  col_headers:
    - LMK_KEY
    - POSTCODE
    - TOTAL_FLOOR_AREA
    - NUMBER_HABITABLE_ROOMS

train:
  numeric_features:
    - date
    - sold_year
    - borough_price_trend
  cat_features:
    - property_type
    - is_new_build
    - is_leasehold
    - district
    - sold_month
  label: price  

feature_engineering:  
  use_district: true
  city_filter:
    city_col: county 
    filter_keywords:
      - london
  timestamp_col: date    

parquet:
  sold_timestamp_col: date
  silver_partition_cols: 
    - sold_year
  bucket_name: london-housing
  destination_blob_name: by_sold_year

